### ISSUE TITLE
Create Pull Request template

### ISSUE THREAD

**Issue by ndouglas** [ndouglas/mistwood#11]
## User Story

As an engineer, I want a PR template so that I can manually check off items in my Definition of Done.

## Tasks

- [x] Create a Pull Request template.
- [x] Insert the Definition of Done (see #10) as a checklist.

## Acceptance Criteria

- [x] Pull Request template exists
