### ISSUE TITLE
Setup and configure Codecov.io

### ISSUE THREAD

**Issue by ndouglas** [ndouglas/mistwood#13]
## User Story

As an engineer, I want to set up and configure Codecov.io so that I have code coverage reports for my pull requests and for the repository as a whole.

## Tasks

- [x] Setup and configure Codecov.io
- [x] Add graph to README

## Acceptance Criteria

- [x] Codecov.io is set up and configured and works on pull requests
- [x] Graph is visible in README
