### ISSUE TITLE
Set up CI/CD pipelines

### ISSUE THREAD

**Issue by ndouglas** [ndouglas/mistwood#14]
## User Story

As an engineer, I want CI/CD pipelines so my project is tested and linted appropriately.

## Tasks

- [x] Set up CI pipeline
  - [x] Linting
  - [x] Clippy
  - [x] Unit tests
  - [x] Integration tests
  - [x] Benchmarks
- [x] Set up CD pipeline
  - [x] Documentation release
  - [ ] (optional) Package release?
  - [ ] (optional) Crates.io?

## Acceptance Criteria
- [x] CI pipeline setup
  - [x] Code is linted automatically and status fails if it fails
  - [x] Code is checked with Clippy automatically and status fails if it fails
  - [x] Code is unit tested automatically and status fails if it fails
  - [x] Code is integration tested automatically and status fails if it fails
- [x] CD pipeline setup
  - [x] Documentation is published to GitHub pages on merge
  - [ ] (optional) package is released
  - [ ] (optional) Crates.io is released
