### ISSUE TITLE
Set up Rustdoc to generate documentation automatically.

### ISSUE THREAD

**Issue by ndouglas** [ndouglas/mistwood#17]
## User Story

As an engineer, I want to generate documentation via Rustdoc automatically so I don't have to manually update documentation about this library.

## Tasks

- [x] Configure Rustdoc to generate documentation in CD.
- [x] Merge Rustdoc with mdbook output.

## Prior Art

See [here](https://github.com/getditto/safer_ffi/blob/5d19ae74f4968ce5d2b9ebc6ba92d9189d07c3bd/scripts/build_docs.sh). 

```bash
#!/bin/bash

set -euxo pipefail

BASE_DIR="$(git rev-parse --show-toplevel)"

cd $BASE_DIR
cargo +nightly doc --all-features
(cd guide
    (cd src && sed -e "s#{ROOT_PATH}#${1-/}#g" links.md.template > links.md)
    mdbook build
    mkdir -p book/{assets,rustdoc}
    cp -r assets/* book/assets/
    cp -r ../target/doc/* book/rustdoc/
)
```

## Acceptance Criteria

- [x] Rustdoc generates documentation.
- [x] This documentation is merged cleanly with mdbook output.
- [x] This happens in the course of the CD pipeline.
