### ISSUE TITLE
Set up Criterion for benchmarking.

### ISSUE THREAD

**Issue by ndouglas** [ndouglas/mistwood#32]
### User Story

As an engineer, I want to set up benchmarking so that I have assurances of performance over time and can identify performance regressions when they occur.

### Tasks

- [ ] Configure [Criterion](https://github.com/bheisler/criterion.rs) and learn how to use it.
- [ ] Configure CI tests to run benchmarks. How do we test on this? 🤔  

### Acceptance Criteria

- [ ] Criterion is configured for the project.
- [ ] At least one benchmark is configured.
- [ ] Benchmarks run as part of CI tests.
- [ ] Performance regressions will cause status checks to fail or will at least trigger a message.
