### ISSUE TITLE
Create event dispatcher pattern.

### ISSUE THREAD

**Issue by ndouglas** [ndouglas/mistwood#33]
### User Story

As an engineer, I want to create a system-wide [event handler](https://willcrichton.net/rust-api-type-patterns/registries.html) so that I can process events in a type-safe manner.

This idea is too beautiful not to use, although I don't have a specific use case for it yet.

### Tasks

- [ ] Figure out how and where to use this.
- [ ] Create event handler.

### Acceptance Criteria

- [ ] I've figured out how and where to use this idea.
- [ ] I've documented the problem that it solves.
- [ ] I feel no sense of embarrassment or shame like I just _yoinked_ an idea and smushed it into this library because it was cool.
- [ ] The event handler exists and is covered by unit tests and is documented appropriately.
