### ISSUE TITLE
Create type-safe Service/Dependency Injection Container.

### ISSUE THREAD

**Issue by ndouglas** [ndouglas/mistwood#34]
### User Story

As an engineer, I want a type-safe service/DI container so that I can do dependency injection with compile-type guarantees.

Yes, this is another idea from [Will Crichton](https://willcrichton.net/rust-api-type-patterns/registries.html). I'd been wondering how to accomplish service containers/ in a sane way, and was blown away by this article.

### Tasks

- [x] Implement the service container (apparently the standard term is DI container, but I've been infected by Symfony's terminology).

### Acceptance Criteria

- [x] Service container exists.
- [x] This is appropriately documented.
- [x] It has appropriate test coverage.
