### ISSUE TITLE
Add `rustc` and `rustdoc` lints.

### ISSUE THREAD

**Issue by ndouglas** [ndouglas/mistwood#42]
### User Story

As an engineer, I want to enable a strict series of lints to ensure that I write idiomatic Rust.

### Tasks

- [ ] Enable appropriate lints from [the rustc book](https://doc.rust-lang.org/rustc/what-is-rustc.html).
- [ ] Enable appropriate lints from [the rustdoc book](https://doc.rust-lang.org/rustdoc/what-is-rustdoc.html).

### Acceptance Criteria

- [ ] Appropriate `rustc` lints have been enabled.
- [ ] Appropriate `rustdoc` lints have been enabled.
