### ISSUE TITLE
Feature breakdown

### ISSUE THREAD

**Issue by ndouglas** [ndouglas/mistwood#6]
## User Story

As an engineer, I need to work through my architectural documentation and component catalog, identify discrete features and feature areas, and open tickets to plan each so that I have a manageable development process.

## Tasks

- [ ] Review documentation
  - [ ] architectural writeup (#2)
  - [ ] initial component catalog (#3)
  - [ ] deeper architectural documentation (#4)
- [ ] Identify discrete features and feature areas
- [ ] Open followup tickets to address each feature or feature area

## Acceptance Criteria

- [ ] Followup tickets opened to address discrete features and feature areas
