### ISSUE TITLE
Review "Rich Storytelling" brainstorming document for enhancement ideas.

### ISSUE THREAD

**Issue by ndouglas** [ndouglas/mistwood#65]
### User Story

As an engineer, I want to review the "Rich Storytelling" brainstorming document I created because I came up with some really good ideas for future development.

### Tasks

- [ ] Review "Rich Storytelling" brainstorming document.
- [ ] Create tickets for interesting ideas.

### Acceptance Criteria

- [ ] Document has been reviewed.
- [ ] Tickets have been created.
