### ISSUE TITLE
Draft feature tickets for enhancing components

### ISSUE THREAD

**Issue by ndouglas** [ndouglas/mistwood#7]
## User Story

As an engineer, I want to record the ideas I've generated thusfar for architectural enhancements, so that I don't have to carry them as a mental load.

## Tasks

- [ ] Collect ideas (written in text documents, tickets in other repositories, Obsidian, etc)
- [ ] Create a ticket for each architectural enhancement idea I have.

## Acceptance Criteria

- [ ] Followup tickets opened for all ideas I've thought up or have recorded in various locations.
