### ISSUE TITLE
Create prompt-and-confirmation logic for requesting confirmation from the player.

### ISSUE THREAD

**Issue by ndouglas** [ndouglas/mistwood#76]
### User Story

As a player, I want to be prompted for confirmation before quitting the game so that I don't accidentally lose progress.

### Tasks

- [ ] Determine a schema for this. We need a template for the prompt itself, and we we need some logic for determining what to do when we've been provided with the player's response.
- [ ] This might include quitting the game, so this ties in with #75.
- [ ] How does this work in the context of an asynchronous game? Some games using this will be multiplayer, some single-player asynchronous games, so how is this handled?

### Acceptance Criteria

- [ ] An approach and suitable implementation has been found for handling confirmation prompts.
