### ISSUE TITLE
Implement basic input parsing.

### ISSUE THREAD

**Issue by ndouglas** [ndouglas/mistwood#81]
### User Story

As a player, I want to be able to provide input to the game.

### Tasks

- [ ] Research a parser. We probably want a pluggable architecture that can support different strategies.
- [ ] Implement a basic parser (like the two-token parser).

### Acceptance Criteria

- [ ] A parser architecture that supports multiple strategies exists.
- [ ] A basic two-token parser exists.
