### ISSUE TITLE
Implement basic commands.

### ISSUE THREAD

**Issue by ndouglas** [ndouglas/mistwood#83]
### User Story

As a player, I want to see the result of my input so that I know what happened.

I think I'll need to start with OOC commands here. Too early to think about actually controlling a character.

### Tasks

- [ ] Pick a couple of basic Zork commands and determine how this can be implemented.
- [ ] Implement command handling pattern and supporting infrastructure.
- [ ] Implement commands.

### Acceptance Criteria

- [ ] Commands can be entered and have some sort of effect.
