### ISSUE TITLE
Implement basic game state.

### ISSUE THREAD

**Issue by ndouglas** [ndouglas/mistwood#86]
### User Story

As an engineer, I need some concept of game state so that I can manage game state.

### Tasks

- [ ] Devise a basic concept of game state.
- [ ] Implement the basic game state.

### Acceptance Criteria

- [ ] Game state concept exists in the game.
