### ISSUE TITLE
Configure Dependabot updates

### ISSUE THREAD

**Issue by ndouglas** [ndouglas/mistwood#9]
## User Story

As an engineer who can't be arsed to update manually, I want Dependabot updates so that I benefit from continuous improvement in other projects.

## Tasks

- [x] Configure and enable Dependabot updates.
- [ ] (Optional) Allow Dependabot to auto-merge if CI/CD tasks complete successfully.

## Acceptance Criteria

- [x] Dependabot updates have been configured for this repository.
